spring.application.name=academia


# Configuração do Banco de Dados
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/academia?charSet=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

api.security.token.secret=${JWT_SECRET:minha_chave_secreta_padrao_local_12345}

server.port=${PORT:8080}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}